services:

  gameoflifeapi:
    image: gameoflifeapi
    build:
      context: GameOfLifeAPI
      dockerfile: Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
    depends_on:
      - "redis_cache"
    restart: always
    links:
      - "redis_cache"
    networks:
      - "net"

 
  redis_cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - "net"

networks:
  net:
    driver: bridge